/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sic_sim_addons_jit_JustInTime */

#ifndef _Included_sic_sim_addons_jit_JustInTime
#define _Included_sic_sim_addons_jit_JustInTime
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     sic_sim_addons_jit_JustInTime
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sic_sim_addons_jit_JustInTime_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     sic_sim_addons_jit_JustInTime
 * Method:    executeAsm
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sic_sim_addons_jit_JustInTime_executeAsm
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
