/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sic_sim_addons_jit_ThrowawayForHeaders */

#ifndef _Included_sic_sim_addons_jit_ThrowawayForHeaders
#define _Included_sic_sim_addons_jit_ThrowawayForHeaders
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sic_sim_addons_jit_ThrowawayForHeaders
 * Method:    execute
 * Signature: ([Lsic/sim/addons/jit/ThrowawayForHeaders/IntelInstr;[Lsic/sim/addons/jit/ThrowawayForHeaders/IntelInstr;)V
 */
JNIEXPORT void JNICALL Java_sic_sim_addons_jit_ThrowawayForHeaders_execute
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     sic_sim_addons_jit_ThrowawayForHeaders
 * Method:    executeAsm
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sic_sim_addons_jit_ThrowawayForHeaders_executeAsm
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
